# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:42:25 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:42:25 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

public-headers += $(module).h
objects += ft_putbool_fd.o
objects += ft_putbool.o
