# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_bzero.o
objects += ft_calloc.o
objects += ft_memalloc.o
objects += ft_memdel.o
objects += ft_memrev.o
objects += ft_memset.o
objects += ft_memset4.o

tests += ft_bzero_test.o
tests += ft_calloc_test.o
tests += ft_memalloc_test.o
tests += ft_memdel_test.o
tests += ft_memrev_test.o
tests += ft_memset_test.o
tests += ft_memset4_test.o

