# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += dprintf
objects += printf
objects += strformat
objects += strformat_len

objects := $(objects:%=ft_%.o)

objects += pf_addchar.o
objects += pf_addcolorbg.o
objects += pf_addcolor.o
objects += pf_addnstr.o
objects += pf_addnum.o
objects += pf_addrgbcolorbg.o
objects += pf_addrgbcolor.o
objects += pf_addstr.o
objects += pf_addtobuff.o
objects += pf_addunum.o
objects += pf_addwchar.o
objects += pf_addwcharstr.o
objects += pf_commands.o
objects += pf_distribute.o
objects += pf_formatbackpad.o
objects += pf_formatchar.o
objects += pf_formatcolor.o
objects += pf_formatdistribute.o
objects += pf_formatdouble.o
objects += pf_formatnum.o
objects += pf_formatpad.o
objects += pf_formatstr.o
objects += pf_formatunum.o
objects += pf_getflag.o
objects += pf_getinfo.o
objects += pf_getlength.o
objects += pf_getprecision.o
objects += pf_gettype.o
objects += pf_getwidth.o
objects += pf_infonew.o
objects += pf_infosetdefault.o
objects += pf_ispositiveint.o
objects += pf_issignint.o
objects += pf_isstr.o
objects += pf_isunsignint.o
objects += pf_iszeropad.o
objects += pf_overflowsigned.o
objects += pf_overflowunsigned.o
objects += pf_setvar_base.o
objects += pf_setvar_type.o
