# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_dprintf
objects += ft_printf
objects += ft_strformat
objects += ft_strformat_len

private-headers += priv.h
objects += ft_addchar
objects += ft_addcolorbg
objects += ft_addcolor
objects += ft_addnstr
objects += ft_addnum
objects += ft_addrgbcolorbg
objects += ft_addrgbcolor
objects += ft_addstr
objects += ft_addtobuff
objects += ft_addunum
objects += ft_addwchar
objects += ft_addwcharstr
objects += ft_commands
objects += ft_distribute
objects += ft_formatbackpad
objects += ft_formatchar
objects += ft_formatcolor
objects += ft_formatdistribute
objects += ft_formatdouble
objects += ft_formatnum
objects += ft_formatpad
objects += ft_formatstr
objects += ft_formatunum
objects += ft_getflag
objects += ft_getinfo
objects += ft_getlength
objects += ft_getprecision
objects += ft_gettype
objects += ft_getwidth
objects += ft_infonew
objects += ft_infosetdefault
objects += ft_ispositiveint
objects += ft_issignint
objects += ft_isstr
objects += ft_isunsignint
objects += ft_iszeropad
objects += ft_overflowsigned
objects += ft_overflowunsigned
objects += ft_setvar_base
objects += ft_setvar_type
