# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_dprintf.o
objects += ft_printf.o
objects += ft_strformat.o
objects += ft_strformat_len.o

private-headers += priv.h
objects += ft_addchar.o
objects += ft_addcolorbg.o
objects += ft_addcolor.o
objects += ft_addnstr.o
objects += ft_addnum.o
objects += ft_addrgbcolorbg.o
objects += ft_addrgbcolor.o
objects += ft_addstr.o
objects += ft_addtobuff.o
objects += ft_addunum.o
objects += ft_addwchar.o
objects += ft_addwcharstr.o
objects += ft_commands.o
objects += ft_distribute.o
objects += ft_formatbackpad.o
objects += ft_formatchar.o
objects += ft_formatcolor.o
objects += ft_formatdistribute.o
objects += ft_formatdouble.o
objects += ft_formatnum.o
objects += ft_formatpad.o
objects += ft_formatstr.o
objects += ft_formatunum.o
objects += ft_getflag.o
objects += ft_getinfo.o
objects += ft_getlength.o
objects += ft_getprecision.o
objects += ft_gettype.o
objects += ft_getwidth.o
objects += ft_infonew.o
objects += ft_infosetdefault.o
objects += ft_ispositiveint.o
objects += ft_issignint.o
objects += ft_isstr.o
objects += ft_isunsignint.o
objects += ft_iszeropad.o
objects += ft_overflowsigned.o
objects += ft_overflowunsigned.o
objects += ft_setvar_base.o
objects += ft_setvar_type.o
