# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_abs.o
objects += ft_atoi_base.o
objects += ft_atoi.o
objects += ft_constrain.o
objects += ft_inrange.o
objects += ft_itoa_base.o
objects += ft_itoa.o
objects += ft_itoa_cbase.o
objects += ft_max.o
objects += ft_min.o
objects += ft_nearestnum.o
objects += ft_normalize.o
objects += ft_numin.o
objects += ft_numlen_base.o
objects += ft_numlen.o
objects += ft_overflow.o
objects += ft_percentage.o
objects += ft_pow.o
objects += ft_putnum_base.o
objects += ft_putnum_base_fd.o
objects += ft_putnum.o
objects += ft_putnum_cbase.o
objects += ft_putnum_cbase_fd.o
objects += ft_putnum_fd.o
objects += ft_sqrt.o
