# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += abs
objects += atoi_base
objects += atoi
objects += constrain
objects += inrange
objects += itoa_base
objects += itoa
objects += itoa_cbase
objects += max
objects += min
objects += nearestnum
objects += normalize
objects += numin
objects += numlen_base
objects += numlen
objects += overflow
objects += percentage
objects += pow
objects += putnum_base
objects += putnum_base_fd
objects += putnum
objects += putnum_cbase
objects += putnum_cbase_fd
objects += putnum_fd
objects += sqrt

objects := $(objects:%=ft_%.o)
