# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_abs
objects += ft_atoi_base
objects += ft_atoi
objects += ft_constrain
objects += ft_inrange
objects += ft_itoa_base
objects += ft_itoa
objects += ft_itoa_cbase
objects += ft_max
objects += ft_min
objects += ft_nearestnum
objects += ft_normalize
objects += ft_numin
objects += ft_numlen_base
objects += ft_numlen
objects += ft_overflow
objects += ft_percentage
objects += ft_pow
objects += ft_putnum_base
objects += ft_putnum_base_fd
objects += ft_putnum
objects += ft_putnum_cbase
objects += ft_putnum_cbase_fd
objects += ft_putnum_fd
objects += ft_sqrt
