# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_getnextdline
objects += ft_getnextline
objects += ft_putendl
objects += ft_putendl_fd
objects += ft_puterror
objects += ft_putline
objects += ft_putline_fd
objects += ft_putnstr
objects += ft_putnstr_fd
objects += ft_putstr
objects += ft_putstr_fd
objects += ft_readfile
objects += ft_strappend
objects += ft_strcat
objects += ft_strchr
objects += ft_strclr
objects += ft_strcmp
objects += ft_strcmp_nocase
objects += ft_strcpy
objects += ft_strdel
objects += ft_strdlen
objects += ft_strdsplit
objects += ft_strdtrim
objects += ft_strdup
objects += ft_strequ
objects += ft_strequ_nocase
objects += ft_strfldnew
objects += ft_strfldvalid
objects += ft_strin
objects += ft_strindex
objects += ft_strisdigit
objects += ft_strisempty
objects += ft_strishex
objects += ft_strislen
objects += ft_striter
objects += ft_striteri
objects += ft_strjoin_arr
objects += ft_strjoin
objects += ft_strjoin_var
objects += ft_strlcat
objects += ft_strlen
objects += ft_strmap
objects += ft_strmapi
objects += ft_strmatch
objects += ft_strmatchlen
objects += ft_strmatchlen_nocase
objects += ft_strncat
objects += ft_strncmp
objects += ft_strncmp_nocase
objects += ft_strncpy
objects += ft_strndup
objects += ft_strnequ
objects += ft_strnequ_nocase
objects += ft_strnew
objects += ft_strnin
objects += ft_strnindex
objects += ft_strnlen
objects += ft_strnstr
objects += ft_strrchr
objects += ft_strreplace
objects += ft_strrev
objects += ft_strsplit
objects += ft_strstr
objects += ft_strsub
objects += ft_strtolower
objects += ft_strtoupper
objects += ft_strtrim
objects += ft_wrddcount

private-headers += priv.h
