# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += getnextdline
objects += getnextline
objects += putendl
objects += putendl_fd
objects += puterror
objects += putline
objects += putline_fd
objects += putnstr
objects += putnstr_fd
objects += putstr
objects += putstr_fd
objects += readfile
objects += strappend
objects += strcat
objects += strchr
objects += strclr
objects += strcmp
objects += strcmp_nocase
objects += strcpy
objects += strdel
objects += strdlen
objects += strdsplit
objects += strdtrim
objects += strdup
objects += strequ
objects += strequ_nocase
objects += strfldnew
objects += strfldvalid
objects += strin
objects += strindex
objects += strisdigit
objects += strisempty
objects += strishex
objects += strislen
objects += striter
objects += striteri
objects += strjoin_arr
objects += strjoin
objects += strjoin_var
objects += strlcat
objects += strlen
objects += strmap
objects += strmapi
objects += strmatch
objects += strmatchlen
objects += strmatchlen_nocase
objects += strncat
objects += strncmp
objects += strncmp_nocase
objects += strncpy
objects += strndup
objects += strnequ
objects += strnequ_nocase
objects += strnew
objects += strnin
objects += strnindex
objects += strnlen
objects += strnstr
objects += strrchr
objects += strreplace
objects += strrev
objects += strsplit
objects += strstr
objects += strsub
objects += strtolower
objects += strtoupper
objects += strtrim
objects += wrddcount

objects := $(objects:%=ft_%.o)
