# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_getnextdline.o
objects += ft_getnextline.o
objects += ft_putendl.o
objects += ft_putendl_fd.o
objects += ft_puterror.o
objects += ft_putline.o
objects += ft_putline_fd.o
objects += ft_putnstr.o
objects += ft_putnstr_fd.o
objects += ft_putstr.o
objects += ft_putstr_fd.o
objects += ft_readfile.o
objects += ft_strappend.o
objects += ft_strcat.o
objects += ft_strchr.o
objects += ft_strclr.o
objects += ft_strcmp.o
objects += ft_strcmp_nocase.o
objects += ft_strcpy.o
objects += ft_strdel.o
objects += ft_strdlen.o
objects += ft_strdsplit.o
objects += ft_strdtrim.o
objects += ft_strdup.o
objects += ft_strequ.o
objects += ft_strequ_nocase.o
objects += ft_strfldnew.o
objects += ft_strfldvalid.o
objects += ft_strin.o
objects += ft_strindex.o
objects += ft_strisdigit.o
objects += ft_strisempty.o
objects += ft_strishex.o
objects += ft_strislen.o
objects += ft_striter.o
objects += ft_striteri.o
objects += ft_strjoin_arr.o
objects += ft_strjoin.o
objects += ft_strjoin_var.o
objects += ft_strlcat.o
objects += ft_strlen.o
objects += ft_strmap.o
objects += ft_strmapi.o
objects += ft_strmatch.o
objects += ft_strmatchlen.o
objects += ft_strmatchlen_nocase.o
objects += ft_strncat.o
objects += ft_strncmp.o
objects += ft_strncmp_nocase.o
objects += ft_strncpy.o
objects += ft_strndup.o
objects += ft_strnequ.o
objects += ft_strnequ_nocase.o
objects += ft_strnew.o
objects += ft_strnin.o
objects += ft_strnindex.o
objects += ft_strnlen.o
objects += ft_strnstr.o
objects += ft_strrchr.o
objects += ft_strreplace.o
objects += ft_strrev.o
objects += ft_strsplit.o
objects += ft_strstr.o
objects += ft_strsub.o
objects += ft_strtolower.o
objects += ft_strtoupper.o
objects += ft_strtrim.o
objects += ft_wrddcount.o

private-headers += priv.h
