# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_chrdin.o
objects += ft_chrdindex.o
objects += ft_chrin.o
objects += ft_chrinbytes.o
objects += ft_chrindex.o
objects += ft_chrnin.o
objects += ft_chrsetbytes.o
objects += ft_getchar.o
objects += ft_isalnum.o
objects += ft_isalpha.o
objects += ft_isascii.o
objects += ft_isblank.o
objects += ft_isdigit.o
objects += ft_islower.o
objects += ft_isprint.o
objects += ft_isspace.o
objects += ft_isupper.o
objects += ft_putchar.o
objects += ft_putchar_fd.o
objects += ft_putnchar.o
objects += ft_putnchar_fd.o
objects += ft_tolower.o
objects += ft_toupper.o
objects += ft_ishex.o
