# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_putstrarr
objects += ft_strarrcpy
objects += ft_strarrcpy_var
objects += ft_strarrdel
objects += ft_strarrdup
objects += ft_strarrdup_var
objects += ft_strarrlen
objects += ft_strarrnew
objects += ft_strarrnlen
objects += ft_strarrnsort
objects += ft_strarrnsortrev
objects += ft_strarrrev
objects += ft_strarrsortac
objects += ft_strarrsort
objects += ft_strarrsortrev
objects += ft_strarrtolower
objects += ft_strarrtolst
objects += ft_strarrtoupper
