# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_putstrarr.o
objects += ft_strarrcpy.o
objects += ft_strarrcpy_var.o
objects += ft_strarrdel.o
objects += ft_strarrdup.o
objects += ft_strarrdup_var.o
objects += ft_strarrlen.o
objects += ft_strarrnew.o
objects += ft_strarrnlen.o
objects += ft_strarrnsort.o
objects += ft_strarrnsortrev.o
objects += ft_strarrrev.o
objects += ft_strarrsortac.o
objects += ft_strarrsort.o
objects += ft_strarrsortrev.o
objects += ft_strarrtolower.o
objects += ft_strarrtolst.o
objects += ft_strarrtoupper.o
