# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += putstrarr
objects += strarrcpy
objects += strarrcpy_var
objects += strarrdel
objects += strarrdup
objects += strarrdup_var
objects += strarrlen
objects += strarrnew
objects += strarrnlen
objects += strarrnsort
objects += strarrnsortrev
objects += strarrrev
objects += strarrsortac
objects += strarrsort
objects += strarrsortrev
objects += strarrtolower
objects += strarrtolst
objects += strarrtoupper

objects := $(objects:%=ft_%.o)
