#$(NAME) = Name of outputfile
#$(INCLUDES) = Path to the includes folder
#$(MAKEINCLUDES) = Path to the makefile includes folder
#$(CCFLAGS) = All the flags that will be used to compile

#Headers libary is dependent on (relative to includes or .)
HEADERS = ../tests/$(NAME).h libft.h

#Additions to the compile flags
CCFLAGS +=

#All source files for test (relative to src/)
#These will be automaticly prefixed with ft_ and sufixed with .c
SRCS = abs atoi_base bzero hashmapnew hashsdbm hashdjb2 hashsdbm_nocase \
	hashdjb2_nocase