# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_numarrsortac.o
objects += ft_numarrsort.o
objects += ft_numarrsortrev.o
objects += ft_numarrtolst.o
objects += ft_putnumarr.o
