# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_termclr
objects += ft_termclr_fd
objects += ft_termcommand
objects += ft_termcommand_fd
objects += ft_termresetcolorbg
objects += ft_termresetcolorbg_fd
objects += ft_termresetcolor
objects += ft_termresetcolor_fd
objects += ft_termsetcolorbg
objects += ft_termsetcolorbg_fd
objects += ft_termsetcolor
objects += ft_termsetcolor_fd
objects += ft_termsetrgbcolorbg
objects += ft_termsetrgbcolorbg_fd
objects += ft_termsetrgbcolor
objects += ft_termsetrgbcolor_fd
