# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += termclr
objects += termclr_fd
objects += termcommand
objects += termcommand_fd
objects += termresetcolorbg
objects += termresetcolorbg_fd
objects += termresetcolor
objects += termresetcolor_fd
objects += termsetcolorbg
objects += termsetcolorbg_fd
objects += termsetcolor
objects += termsetcolor_fd
objects += termsetrgbcolorbg
objects += termsetrgbcolorbg_fd
objects += termsetrgbcolor
objects += termsetrgbcolor_fd

objects := $(objects:%=ft_%.o)
