# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += hashdjb2a
objects += hashdjb2a_nocase
objects += hashdjb2
objects += hashdjb2_nocase
objects += hashmapadd
objects += hashmapadd_str
objects += hashmapdel
objects += hashmapdelone
objects += hashmapdelone_str
objects += hashmapget
objects += hashmapget_str
objects += hashmapnew
objects += hashsdbm
objects += hashsdbm_nocase

objects := $(objects:%=ft_%.o)
objects += hs_keyequ.o
