# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

public-headers += $(module).h
objects += ft_hashdjb2a.o
objects += ft_hashdjb2a_nocase.o
objects += ft_hashdjb2.o
objects += ft_hashdjb2_nocase.o
objects += ft_hashmapadd.o
objects += ft_hashmapadd_str.o
objects += ft_hashmapdel.o
objects += ft_hashmapdelone.o
objects += ft_hashmapdelone_str.o
objects += ft_hashmapget.o
objects += ft_hashmapget_str.o
objects += ft_hashmapnew.o
objects += ft_hashsdbm.o
objects += ft_hashsdbm_nocase.o

private-headers += priv.h
objects += ft_keyequ.o
