# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_hashdjb2a
objects += ft_hashdjb2a_nocase
objects += ft_hashdjb2
objects += ft_hashdjb2_nocase
objects += ft_hashmapadd
objects += ft_hashmapadd_str
objects += ft_hashmapdel
objects += ft_hashmapdelone
objects += ft_hashmapdelone_str
objects += ft_hashmapget
objects += ft_hashmapget_str
objects += ft_hashmapnew
objects += ft_hashsdbm
objects += ft_hashsdbm_nocase

private-headers += priv.h
objects += ft_keyequ
