# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_convert_color_to_argb.o
objects += ft_convert_argb_to_color.o
tests += ft_convert_color_to_argb_test.o
tests += ft_convert_argb_to_color_test.o

objects += ft_convert_color_to_hex.o
objects += ft_convert_hex_to_color.o
tests += ft_convert_color_to_hex_test.o
tests += ft_convert_hex_to_color_test.o

# objects += ft_mix_argb.o
# objects += ft_set_argb_intensity.o
