# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_colorcode.o
objects += ft_colorhextorgba.o
objects += ft_colorlcode.o
objects += ft_colorncode.o
objects += ft_colorrgbatohex.o
objects += ft_colorstr.o
