# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += lstaddbck
objects += lstadd
objects += lstdel
objects += lstdelmem
objects += lstdelone
objects += lstdup
objects += lstdupone
objects += lstfindadd_content
objects += lstfindadd_size
objects += lstfind_content
objects += lstfind_size
objects += lstindex
objects += lstinsert
objects += lstiter
objects += lstlast
objects += lstlen
objects += lstmap
objects += lstnew
objects += lstnew_dup
objects += lstnlen
objects += lstrev
objects += lstsort
objects += lstsortrev
objects += lstsortstrac
objects += lsttonumarr
objects += lsttostrarr
objects += lstunlink
objects += putlstsize
objects += putnumlst
objects += putstrlst

objects := $(objects:%=ft_%.o)
