# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_lstaddbck
objects += ft_lstadd
objects += ft_lstdel
objects += ft_lstdelmem
objects += ft_lstdelone
objects += ft_lstdup
objects += ft_lstdupone
objects += ft_lstfindadd_content
objects += ft_lstfindadd_size
objects += ft_lstfind_content
objects += ft_lstfind_size
objects += ft_lstindex
objects += ft_lstinsert
objects += ft_lstiter
objects += ft_lstlast
objects += ft_lstlen
objects += ft_lstmap
objects += ft_lstnew
objects += ft_lstnew_dup
objects += ft_lstnlen
objects += ft_lstrev
objects += ft_lstsort
objects += ft_lstsortrev
objects += ft_lstsortstrac
objects += ft_lsttonumarr
objects += ft_lsttostrarr
objects += ft_lstunlink
objects += ft_putlstsize
objects += ft_putnumlst
objects += ft_putstrlst
