# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_bzero.o
objects += ft_memalloc.o
objects += ft_memccpy.o
objects += ft_memchr.o
objects += ft_memcmp.o
objects += ft_memcpy.o
objects += ft_memdel.o
objects += ft_memdup.o
objects += ft_memequ.o
objects += ft_memindex.o
objects += ft_memmove.o
objects += ft_memrchr.o
objects += ft_memrcpy.o
objects += ft_memset4.o
objects += ft_memset.o
objects += ft_memrev.o
objects += ft_pointerreplace.o
objects += ft_putbytes.o
objects += ft_putmemory.o
objects += ft_putpointer.o
objects += ft_swap.o
