# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_bzero
objects += ft_memalloc
objects += ft_memccpy
objects += ft_memchr
objects += ft_memcmp
objects += ft_memcpy
objects += ft_memdel
objects += ft_memdup
objects += ft_memequ
objects += ft_memindex
objects += ft_memmove
objects += ft_memrchr
objects += ft_memrcpy
objects += ft_memset4
objects += ft_memset
objects += ft_pointerreplace
objects += ft_putbytes
objects += ft_putmemory
objects += ft_putpointer
objects += ft_swap
