# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += bzero
objects += memalloc
objects += memccpy
objects += memchr
objects += memcmp
objects += memcpy
objects += memdel
objects += memdup
objects += memequ
objects += memindex
objects += memmove
objects += memrchr
objects += memrcpy
objects += memset4
objects += memset
objects += pointerreplace
objects += putbytes
objects += putmemory
objects += putpointer
objects += swap

objects := $(objects:%=ft_%.o)
