# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_putunum_base
objects += ft_putunum_base_fd
objects += ft_putunum
objects += ft_putunum_cbase
objects += ft_putunum_cbase_fd
objects += ft_putunum_fd
objects += ft_unumlen_base
objects += ft_unumlen
