# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += putunum_base
objects += putunum_base_fd
objects += putunum
objects += putunum_cbase
objects += putunum_cbase_fd
objects += putunum_fd
objects += unumlen_base
objects += unumlen

objects := $(objects:%=ft_%.o)
