# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_termclr.o
objects += ft_termclr_fd.o
objects += ft_termcommand.o
objects += ft_termcommand_fd.o
objects += ft_termresetcolorbg.o
objects += ft_termresetcolorbg_fd.o
objects += ft_termresetcolor.o
objects += ft_termresetcolor_fd.o
objects += ft_termsetcolorbg.o
objects += ft_termsetcolorbg_fd.o
objects += ft_termsetcolor.o
objects += ft_termsetcolor_fd.o
objects += ft_termsetrgbcolorbg.o
objects += ft_termsetrgbcolorbg_fd.o
objects += ft_termsetrgbcolor.o
objects += ft_termsetrgbcolor_fd.o
