# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_putnutf8str
objects += ft_putnutf8str_fd
objects += ft_pututf8
objects += ft_pututf8_fd
objects += ft_pututf8str
objects += ft_pututf8str_fd
objects += ft_utf8len
objects += ft_utf8strlen
objects += ft_utf8strnlen
