# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += putnutf8str
objects += putnutf8str_fd
objects += pututf8
objects += pututf8_fd
objects += pututf8str
objects += pututf8str_fd
objects += utf8len
objects += utf8strlen
objects += utf8strnlen

objects := $(objects:%=ft_%.o)
