#$(NAME) = Name of outputfile

#Headers libary is dependent on (relative to includes)
HEADERS = ft_$(NAME).h

#Additions to the compile flags (-Wall -Wextra -Werror allready included)
CCFLAGS +=

#Source file prefix
PREFIX =

#All ft_ source files for the sublib (relative to src/$(SRCFOLDER)/)
FT_SRCS = hashdjb hashdjb_nocase hashmapadd hashmapnew hashsdbm \
	hashsdbm_nocase

#All source files for the sublib (relative to src/$(SRCFOLDER)/)
SRCS =
