#$(NAME) = Name of outputfile

#Headers libary is dependent on (relative to includes)
HEADERS = ft_$(NAME).h

#Additions to the compile flags (-Wall -Wextra -Werror allready included)
CCFLAGS +=

#Source file prefix
PREFIX =

#All ft_ source files for the sublib (relative to src/$(SRCFOLDER)/)
FT_SRCS = putunum putunum_base putunum_base_fd putunum_cbase putunum_cbase_fd \
	putunum_fd unumlen unumlen_base

#All source files for the sublib (relative to src/$(SRCFOLDER)/)
SRCS =
