# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += chrdin
objects += chrdindex
objects += chrin
objects += chrinbytes
objects += chrindex
objects += chrnin
objects += chrsetbytes
objects += chrtostr
objects += getchar
objects += isalnum
objects += isalpha
objects += isascii
objects += isblank
objects += isdigit
objects += islower
objects += isprint
objects += isspace
objects += isupper
objects += putchar
objects += putchar_fd
objects += putnchar
objects += putnchar_fd
objects += tolower
objects += toupper
objects += ishex

objects := $(objects:%=ft_%.o)
