# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_chrdin
objects += ft_chrdindex
objects += ft_chrin
objects += ft_chrinbytes
objects += ft_chrindex
objects += ft_chrnin
objects += ft_chrsetbytes
objects += ft_chrtostr
objects += ft_getchar
objects += ft_isalnum
objects += ft_isalpha
objects += ft_isascii
objects += ft_isblank
objects += ft_isdigit
objects += ft_islower
objects += ft_isprint
objects += ft_isspace
objects += ft_isupper
objects += ft_putchar
objects += ft_putchar_fd
objects += ft_putnchar
objects += ft_putnchar_fd
objects += ft_tolower
objects += ft_toupper
objects += ft_ishex
