# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.oodam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += add_tpool_ttask
objects += del_tpool
objects += del_ttask
objects += get_core_count
objects += join_tpool
objects += join_ttask
objects += join_ttasks
objects += new_tpool
objects += new_ttask
objects += run_thread

objects := $(objects:%=ft_%.o)

objects += th_add_tqueue_ttask.o
objects += th_alloc_tpool_tthreads.o
objects += th_complete_ttask.o
objects += th_del_tqueue.o
objects += th_del_tthread.o
objects += th_get_ttask.o
objects += th_new_tqueue.o
objects += th_new_tthread.o
objects += th_run_ttask.o
objects += th_worker_tthread.o
