# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.oodam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_add_tpool_ttask.o
objects += ft_del_tpool.o
objects += ft_del_ttask.o
objects += ft_get_core_count.o
objects += ft_join_tpool.o
objects += ft_join_ttask.o
objects += ft_join_ttasks.o
objects += ft_new_tpool.o
objects += ft_new_ttask.o
objects += ft_run_thread.o

private-headers += priv.h
objects += ft_add_tqueue_ttask.o
objects += ft_alloc_tpool_tthreads.o
objects += ft_complete_ttask.o
objects += ft_del_tqueue.o
objects += ft_del_tthread.o
objects += ft_get_ttask.o
objects += ft_new_tqueue.o
objects += ft_new_tthread.o
objects += ft_run_ttask.o
objects += ft_worker_tthread.o
