# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.oodam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster       #+#    #+#                 #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_add_tpool_ttask
objects += ft_del_tpool
objects += ft_del_ttask
objects += ft_get_core_count
objects += ft_join_tpool
objects += ft_join_ttask
objects += ft_join_ttasks
objects += ft_new_tpool
objects += ft_new_ttask
objects += ft_run_thread

private-headers += priv.h
objects += ft_add_tqueue_ttask
objects += ft_alloc_tpool_tthreads
objects += ft_complete_ttask
objects += ft_del_tqueue
objects += ft_del_tthread
objects += ft_get_ttask
objects += ft_new_tqueue
objects += ft_new_tthread
objects += ft_run_ttask
objects += ft_worker_tthread
