# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: pholster <pholster@student.codam.nl>         +#+                      #
#                                                    +#+                       #
#    Created: 2020/02/15 16:43:36 by pholster      #+#    #+#                  #
#    Updated: 2020/02/15 16:43:36 by pholster      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

objects += ft_lstaddbck.o
objects += ft_lstadd.o
objects += ft_lstdel.o
objects += ft_lstdelmem.o
objects += ft_lstdelone.o
objects += ft_lstdup.o
objects += ft_lstdupone.o
objects += ft_lstfindadd_content.o
objects += ft_lstfindadd_size.o
objects += ft_lstfind_content.o
objects += ft_lstfind_size.o
objects += ft_lstindex.o
objects += ft_lstinsert.o
objects += ft_lstiter.o
objects += ft_lstlast.o
objects += ft_lstlen.o
objects += ft_lstmap.o
objects += ft_lstnew.o
objects += ft_lstnew_dup.o
objects += ft_lstnlen.o
objects += ft_lstrev.o
objects += ft_lstsort.o
objects += ft_lstsortrev.o
objects += ft_lstsortstrac.o
objects += ft_lsttonumarr.o
objects += ft_lsttostrarr.o
objects += ft_lstunlink.o
objects += ft_putlstsize.o
objects += ft_putnumlst.o
objects += ft_putstrlst.o
