name: libft CI Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: bash ci/install.bash

      - name: Compile
        run: make

      - name: Test
        run: make test GCOV=true

      - name: Upload GCOV
        run: |
          export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/2.7/bin
          export PATH=$PATH:$HOME/.local/bin
          bash ci/gcov.bash
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.coverallsRepoToken }}

  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: docInfo
        run: ./tools/docInfo.py
