name: C-Tests

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    
    steps:
    - name: Install
      run: bash .travisInstall.bash
      uses: ./.travisInstall.bash
    - name: Run Test
      run: bash .travisScript.bash
      uses: ./.travisScript.bash
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -X gcov
